### ISSUE TITLE
Ideas for updates 2

### ISSUE THREAD

**Issue by thewaydev** [seamuskills/rpg-combat-durability#4]
These are more ideas,

- [ ] New weapons for late game.
- [ ] Abilities for weapons.
- [ ] New menu so you can choose where to go, shop, main menu, etc.
- [ ] New building idea, bank.

**Comment by seamuskills** [comment]
idk some of this might require a rework of almost the entire system... maybe if we made another game together
new weapons and abilities though... sure i guess.

**Comment by thewaydev** [comment]
Sorry these don't all have to be done.
