### ISSUE TITLE
new feature: rings

### ISSUE THREAD

**Issue by seamuskills** [seamuskills/rpg-combat-durability#5]
I have been thinking about it for a while, I would like to add rings.
rings have temporary buffs. my Idea is you can buy 4 kinds of rings, unenchanted, armor, health, regeneration.
more rings can be added later.
you may only equip one, but own as many as you like (but only one of each type).
current ring variant ideas:
armor: temporary ap bonus (ring degrades over a certain amount of turns)
health: temporary maxhp upgrade, degrades whenever hurt (when equipped it restores your percentage of hp so if you had 50/100 going to 150 maxhp your current hp would be changed to 75hp)
regeneration: every combat turn regens 5% of your hp, low durability, degrades every turn.
unenchanted: this is what degraded rings turn into, you may enchant them in the shop to turn into a random other ring type, this is the only type directly purchasable

this is planned unless you veto it. feedback on my ideas is appreciated!

**Comment by seamuskills** [comment]
from now on I will make it a habit to post upcoming updates here, so we can brainstorm and stuff before jumping right into the coding.

**Comment by thewaydev** [comment]
Thats a good idea.

**Comment by seamuskills** [comment]
rings added
